// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ResumeAnalyzer.Data;

#nullable disable

namespace ResumeAnalyzer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.AnalysisResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AtsScore")
                        .HasColumnType("int");

                    b.Property<int?>("JobDescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("JobMatchScore")
                        .HasColumnType("int");

                    b.Property<string>("MatchedSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissingSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<int>("ResumeScore")
                        .HasColumnType("int");

                    b.Property<string>("Suggestions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("JobDescriptionId");

                    b.HasIndex("ResumeId");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.InterviewQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("InterviewQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Conceptual",
                            Level = "Beginner",
                            Question = "Explain the MVC architecture pattern in ASP.NET Core.",
                            SkillName = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Technical",
                            Level = "Intermediate",
                            Question = "What is middleware in ASP.NET Core and how does it work?",
                            SkillName = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Technical",
                            Level = "Advanced",
                            Question = "Explain dependency injection and how it's implemented in ASP.NET Core.",
                            SkillName = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Conceptual",
                            Level = "Beginner",
                            Question = "What is the difference between value types and reference types in C#?",
                            SkillName = "C#"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Technical",
                            Level = "Intermediate",
                            Question = "Explain async/await and how they work in C#.",
                            SkillName = "C#"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Technical",
                            Level = "Advanced",
                            Question = "What are LINQ expressions and when would you use them?",
                            SkillName = "C#"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Conceptual",
                            Level = "Beginner",
                            Question = "What is normalization in SQL and what are its normal forms?",
                            SkillName = "SQL"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Technical",
                            Level = "Intermediate",
                            Question = "Explain the difference between INNER JOIN, LEFT JOIN, and RIGHT JOIN.",
                            SkillName = "SQL"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Technical",
                            Level = "Advanced",
                            Question = "What are stored procedures and when should you use them?",
                            SkillName = "SQL"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Conceptual",
                            Level = "Beginner",
                            Question = "What is the difference between let, var, and const in JavaScript?",
                            SkillName = "JavaScript"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Technical",
                            Level = "Intermediate",
                            Question = "Explain closures and how they work in JavaScript.",
                            SkillName = "JavaScript"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Technical",
                            Level = "Advanced",
                            Question = "What are Promises and how do they differ from async/await?",
                            SkillName = "JavaScript"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Conceptual",
                            Level = "Beginner",
                            Question = "What are Python decorators and how are they used?",
                            SkillName = "Python"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Technical",
                            Level = "Intermediate",
                            Question = "Explain list comprehensions and generators in Python.",
                            SkillName = "Python"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Technical",
                            Level = "Advanced",
                            Question = "What is GIL in Python and how does it affect multithreading?",
                            SkillName = "Python"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Conceptual",
                            Level = "Beginner",
                            Question = "What is the virtual DOM and how does React use it?",
                            SkillName = "React"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Technical",
                            Level = "Intermediate",
                            Question = "Explain React hooks and the useEffect hook.",
                            SkillName = "React"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Technical",
                            Level = "Advanced",
                            Question = "What is Redux and when would you use it over React Context?",
                            SkillName = "React"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Conceptual",
                            Level = "Beginner",
                            Question = "What is the difference between supervised and unsupervised learning?",
                            SkillName = "Machine Learning"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Technical",
                            Level = "Intermediate",
                            Question = "Explain overfitting and how to prevent it.",
                            SkillName = "Machine Learning"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Technical",
                            Level = "Advanced",
                            Question = "What is gradient descent and how does it work?",
                            SkillName = "Machine Learning"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Conceptual",
                            Level = "Beginner",
                            Question = "What is Docker and how does it differ from a virtual machine?",
                            SkillName = "Docker"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Technical",
                            Level = "Intermediate",
                            Question = "What is a Dockerfile and how do you create a Docker image?",
                            SkillName = "Docker"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Technical",
                            Level = "Advanced",
                            Question = "Explain Docker Compose and multi-container orchestration.",
                            SkillName = "Docker"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Conceptual",
                            Level = "Beginner",
                            Question = "What is the difference between git merge and git rebase?",
                            SkillName = "Git"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Technical",
                            Level = "Intermediate",
                            Question = "Explain the Git branching strategy for large teams.",
                            SkillName = "Git"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Conceptual",
                            Level = "Beginner",
                            Question = "What are the principles of RESTful API design?",
                            SkillName = "REST API"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Technical",
                            Level = "Intermediate",
                            Question = "How do you handle authentication in a REST API (JWT vs OAuth)?",
                            SkillName = "REST API"
                        });
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.JobDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("JobDescriptions");
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ResumeId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.Resume", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AtsScore")
                        .HasColumnType("int");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ParsedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParsedName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParsedPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParsedSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ResumeScore")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Resumes");
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.ResumeSkill", b =>
                {
                    b.Property<int>("ResumeId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.HasKey("ResumeId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("ResumeSkills");
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Proficiency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Backend",
                            Name = "ASP.NET Core",
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Backend",
                            Name = "C#",
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Frontend",
                            Name = "JavaScript",
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Backend",
                            Name = "Python",
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Database",
                            Name = "SQL",
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Frontend",
                            Name = "React",
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Frontend",
                            Name = "HTML",
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Frontend",
                            Name = "CSS",
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            Id = 9,
                            Category = "AI",
                            Name = "Machine Learning",
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            Id = 10,
                            Category = "DevOps",
                            Name = "Docker",
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            Id = 11,
                            Category = "DevOps",
                            Name = "Git",
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Cloud",
                            Name = "Azure",
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Backend",
                            Name = "Node.js",
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Frontend",
                            Name = "Angular",
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Frontend",
                            Name = "Vue.js",
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Frontend",
                            Name = "TypeScript",
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Database",
                            Name = "MongoDB",
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Database",
                            Name = "PostgreSQL",
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Backend",
                            Name = "REST API",
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Architecture",
                            Name = "Microservices",
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            Id = 21,
                            Category = "DevOps",
                            Name = "Kubernetes",
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Cloud",
                            Name = "AWS",
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Backend",
                            Name = "Java",
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Backend",
                            Name = "Spring Boot",
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            Id = 25,
                            Category = "AI",
                            Name = "TensorFlow",
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            Id = 26,
                            Category = "AI",
                            Name = "Deep Learning",
                            Proficiency = "Advanced"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Data",
                            Name = "Data Analysis",
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Data",
                            Name = "Power BI",
                            Proficiency = "Intermediate"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Methodology",
                            Name = "Agile",
                            Proficiency = "Beginner"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Methodology",
                            Name = "Scrum",
                            Proficiency = "Beginner"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ResumeAnalyzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ResumeAnalyzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumeAnalyzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ResumeAnalyzer.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.AnalysisResult", b =>
                {
                    b.HasOne("ResumeAnalyzer.Models.JobDescription", "JobDescription")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("JobDescriptionId");

                    b.HasOne("ResumeAnalyzer.Models.Resume", "Resume")
                        .WithMany("AnalysisResults")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDescription");

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.JobDescription", b =>
                {
                    b.HasOne("ResumeAnalyzer.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.Report", b =>
                {
                    b.HasOne("ResumeAnalyzer.Models.Resume", "Resume")
                        .WithMany("Reports")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.Resume", b =>
                {
                    b.HasOne("ResumeAnalyzer.Models.ApplicationUser", "User")
                        .WithMany("Resumes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.ResumeSkill", b =>
                {
                    b.HasOne("ResumeAnalyzer.Models.Resume", "Resume")
                        .WithMany("ResumeSkills")
                        .HasForeignKey("ResumeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ResumeAnalyzer.Models.Skill", "Skill")
                        .WithMany("ResumeSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Resume");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.ApplicationUser", b =>
                {
                    b.Navigation("Resumes");
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.JobDescription", b =>
                {
                    b.Navigation("AnalysisResults");
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.Resume", b =>
                {
                    b.Navigation("AnalysisResults");

                    b.Navigation("Reports");

                    b.Navigation("ResumeSkills");
                });

            modelBuilder.Entity("ResumeAnalyzer.Models.Skill", b =>
                {
                    b.Navigation("ResumeSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
